// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-07-15 23:04:11.964684669 +0800 CST m=+0.377462702

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "Zeus 宙斯权限后台",
        "title": "Zeus 宙斯权限后台 API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@bullteam.cn"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "V0.1"
    },
    "host": "api.bullteam.cn",
    "paths": {
        "/test": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "测试",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/account/domains": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取用户管理域",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"result\":[]}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/account/info": {
            "get": {
                "description": "登陆用户信息接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "登录用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1,\"name\":\"wutong\"}}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    }
                }
            }
        },
        "/v1/account/password": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新个人密码",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/api/roles": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "角色列表[分页+搜索]",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"result\":[...],\"total\":1}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/api/roles/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "角色信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1,\"name\":\"test\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/api/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "新增用户",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/api/users/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "用户信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1,\"name\":\"wutong\"}}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    },
                    "400": {
                        "description": "{\"code\":10004,\"msg\": \"用户信息不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新用户密码",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "删除用户",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/depts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "新增应用",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/depts/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "部门信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1,\"name\":\"test\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/domains": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "新增应用",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/domains/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "项目信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{\"id\":1,\"name\":\"test\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.User": {
            "type": "object",
            "properties": {
                "created_time": {
                    "type": "string",
                    "example": "2019-07-10 0:39"
                },
                "department_id": {
                    "type": "integer",
                    "example": 1
                },
                "email": {
                    "type": "string",
                    "example": "xxxx@hotmail.com"
                },
                "faceicon": {
                    "type": "string",
                    "example": "http://xxx.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "mobile": {
                    "type": "string",
                    "example": "186000000"
                },
                "realname": {
                    "type": "string",
                    "example": "黄梧桐"
                },
                "sex": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "title"
                },
                "updated_time": {
                    "type": "string",
                    "example": "2019-07-10 0:39"
                },
                "username": {
                    "type": "string",
                    "example": "wutongci"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
